### PR TITLE
[Mermaid] Cfg Printer Improvents and Fixes

### LINKED ISSUE #2231: [Diagram]: Cfg Diagram Improvements
- [ ] Simplified Version should not show the Basic Block label
- [ ] Make colors for CFG configurable
- [ ] Prevent nodeids from leaking into the diagram when basic blocks are enabled, and only a part of the diagram is highlighted.

### PR DESCRIPTION
**Pull request by gigalasr**
closes #2231

### CODE REVIEW

File: src/util/mermaid/cfg.ts [hunk 1]
```diff
@@ -79,13 +104,23 @@ export function cfgToMermaid(cfg: ControlFlowInformation, normalizedAst: Normali
...
 		if(vertex.type === CfgVertexType.Block) {
 			if(simplify) {
+				if(includeOnlyIds && !vertex.elems.some(elem => includeOnlyIds.has(elem.id))) {
+					continue;
+				}
+
 				const ids = vertex.elems?.map(e => e.id) ?? [];
 				const reconstruct = reconstructToCode(normalizedAst, { nodes: new Set(ids) }, doNotAutoSelect).code;
-				const name = `"\`Basic Block (${id})\n${escapeMarkdown(reconstruct)}\`"`;
+				const name = `"\`(${id})\n${escapeMarkdown(reconstruct)}\`"`;
```
Comment (EagleoutIce) [inline src/util/mermaid/cfg.ts]: I wanted this to be configurable 🙈  + just having a `(id)` in the first line... feels weird don't you think? maybe remove it then alltogether? or just print their source range?

**Review by EagleoutIce — APPROVED** [review]

**Comment by EagleoutIce** [comment]
_This pull request is included in v2.8.7 (see [Release v2.8.7 (Robustified Use-Method Support and ifelse fixes (retry))](https://github.com/flowr-analysis/flowr/releases/tag/v2.8.7))._
